function ma = get_ma_vector(m2, m3, r2, r3)%What goes inside the brackets is an example. Fill it up as desired.
% sind and cosd are in degrees

% Enter elements into your ma ventor from your hand calculations:

ma = [   0;...
         0;...
         0;...
         0;...
         0;...
         0;...
         0;...
         0 ...
    ];

end